/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as publicRouteRouteImport } from './routes/(public)/route'
import { Route as publicIndexRouteImport } from './routes/(public)/index'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as ApiUploadRouteImport } from './routes/api/upload'
import { Route as publicLayoutsIndexRouteImport } from './routes/(public)/layouts/index'
import { Route as LayoutsSlugPreviewRouteImport } from './routes/layouts/$slug.preview'
import { Route as LayoutsSlugEditorRouteImport } from './routes/layouts/$slug.editor'
import { Route as ApiScreenshotGenerateRouteImport } from './routes/api/screenshot/generate'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as publicLayoutsSlugRouteImport } from './routes/(public)/layouts/$slug'

const publicRouteRoute = publicRouteRouteImport.update({
  id: '/(public)',
  getParentRoute: () => rootRouteImport,
} as any)
const publicIndexRoute = publicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => publicRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadRoute = ApiUploadRouteImport.update({
  id: '/api/upload',
  path: '/api/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const publicLayoutsIndexRoute = publicLayoutsIndexRouteImport.update({
  id: '/layouts/',
  path: '/layouts/',
  getParentRoute: () => publicRouteRoute,
} as any)
const LayoutsSlugPreviewRoute = LayoutsSlugPreviewRouteImport.update({
  id: '/layouts/$slug/preview',
  path: '/layouts/$slug/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutsSlugEditorRoute = LayoutsSlugEditorRouteImport.update({
  id: '/layouts/$slug/editor',
  path: '/layouts/$slug/editor',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiScreenshotGenerateRoute = ApiScreenshotGenerateRouteImport.update({
  id: '/api/screenshot/generate',
  path: '/api/screenshot/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const publicLayoutsSlugRoute = publicLayoutsSlugRouteImport.update({
  id: '/layouts/$slug',
  path: '/layouts/$slug',
  getParentRoute: () => publicRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/api/upload': typeof ApiUploadRoute
  '/auth/login': typeof AuthLoginRoute
  '/': typeof publicIndexRoute
  '/layouts/$slug': typeof publicLayoutsSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/screenshot/generate': typeof ApiScreenshotGenerateRoute
  '/layouts/$slug/editor': typeof LayoutsSlugEditorRoute
  '/layouts/$slug/preview': typeof LayoutsSlugPreviewRoute
  '/layouts': typeof publicLayoutsIndexRoute
}
export interface FileRoutesByTo {
  '/api/upload': typeof ApiUploadRoute
  '/auth/login': typeof AuthLoginRoute
  '/': typeof publicIndexRoute
  '/layouts/$slug': typeof publicLayoutsSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/screenshot/generate': typeof ApiScreenshotGenerateRoute
  '/layouts/$slug/editor': typeof LayoutsSlugEditorRoute
  '/layouts/$slug/preview': typeof LayoutsSlugPreviewRoute
  '/layouts': typeof publicLayoutsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(public)': typeof publicRouteRouteWithChildren
  '/api/upload': typeof ApiUploadRoute
  '/auth/login': typeof AuthLoginRoute
  '/(public)/': typeof publicIndexRoute
  '/(public)/layouts/$slug': typeof publicLayoutsSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/screenshot/generate': typeof ApiScreenshotGenerateRoute
  '/layouts/$slug/editor': typeof LayoutsSlugEditorRoute
  '/layouts/$slug/preview': typeof LayoutsSlugPreviewRoute
  '/(public)/layouts/': typeof publicLayoutsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/api/upload'
    | '/auth/login'
    | '/'
    | '/layouts/$slug'
    | '/api/auth/$'
    | '/api/screenshot/generate'
    | '/layouts/$slug/editor'
    | '/layouts/$slug/preview'
    | '/layouts'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/api/upload'
    | '/auth/login'
    | '/'
    | '/layouts/$slug'
    | '/api/auth/$'
    | '/api/screenshot/generate'
    | '/layouts/$slug/editor'
    | '/layouts/$slug/preview'
    | '/layouts'
  id:
    | '__root__'
    | '/(public)'
    | '/api/upload'
    | '/auth/login'
    | '/(public)/'
    | '/(public)/layouts/$slug'
    | '/api/auth/$'
    | '/api/screenshot/generate'
    | '/layouts/$slug/editor'
    | '/layouts/$slug/preview'
    | '/(public)/layouts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  publicRouteRoute: typeof publicRouteRouteWithChildren
  ApiUploadRoute: typeof ApiUploadRoute
  AuthLoginRoute: typeof AuthLoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiScreenshotGenerateRoute: typeof ApiScreenshotGenerateRoute
  LayoutsSlugEditorRoute: typeof LayoutsSlugEditorRoute
  LayoutsSlugPreviewRoute: typeof LayoutsSlugPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(public)': {
      id: '/(public)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof publicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/': {
      id: '/(public)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicIndexRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload': {
      id: '/api/upload'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/layouts/': {
      id: '/(public)/layouts/'
      path: '/layouts'
      fullPath: '/layouts'
      preLoaderRoute: typeof publicLayoutsIndexRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/layouts/$slug/preview': {
      id: '/layouts/$slug/preview'
      path: '/layouts/$slug/preview'
      fullPath: '/layouts/$slug/preview'
      preLoaderRoute: typeof LayoutsSlugPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/layouts/$slug/editor': {
      id: '/layouts/$slug/editor'
      path: '/layouts/$slug/editor'
      fullPath: '/layouts/$slug/editor'
      preLoaderRoute: typeof LayoutsSlugEditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/screenshot/generate': {
      id: '/api/screenshot/generate'
      path: '/api/screenshot/generate'
      fullPath: '/api/screenshot/generate'
      preLoaderRoute: typeof ApiScreenshotGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/layouts/$slug': {
      id: '/(public)/layouts/$slug'
      path: '/layouts/$slug'
      fullPath: '/layouts/$slug'
      preLoaderRoute: typeof publicLayoutsSlugRouteImport
      parentRoute: typeof publicRouteRoute
    }
  }
}

interface publicRouteRouteChildren {
  publicIndexRoute: typeof publicIndexRoute
  publicLayoutsSlugRoute: typeof publicLayoutsSlugRoute
  publicLayoutsIndexRoute: typeof publicLayoutsIndexRoute
}

const publicRouteRouteChildren: publicRouteRouteChildren = {
  publicIndexRoute: publicIndexRoute,
  publicLayoutsSlugRoute: publicLayoutsSlugRoute,
  publicLayoutsIndexRoute: publicLayoutsIndexRoute,
}

const publicRouteRouteWithChildren = publicRouteRoute._addFileChildren(
  publicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  publicRouteRoute: publicRouteRouteWithChildren,
  ApiUploadRoute: ApiUploadRoute,
  AuthLoginRoute: AuthLoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiScreenshotGenerateRoute: ApiScreenshotGenerateRoute,
  LayoutsSlugEditorRoute: LayoutsSlugEditorRoute,
  LayoutsSlugPreviewRoute: LayoutsSlugPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
